# Generated by Django 6.1.1 on 2026-10-04 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_verificada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resultado_verificacion', models.CharField(blank=True, choices=[('ok', 'OK'), ('ng', 'NG')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cif', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(help_text='Dirección a la que se envía la orden autorizada', max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del operario de Almacén')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('gestion_compras', models.TextField(blank=True, help_text='Resolución gestionada por Compras')),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='pedidos.lineapedido')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('en_camino', 'En camino'), ('incidencia', 'Incidencia'), ('incidencia_resuelta', 'Incidencia resuelta'), ('recibido', 'Recibido')], default='creada', max_length=25)),
                ('notificar_produccion', models.BooleanField(default=True)),
                ('notificar_compras', models.BooleanField(default=False)),
                ('notificar_administracion', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.ordencompra'),
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=25)),
                ('estado_nuevo', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.ordencompra')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='pedidos.proveedor'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.unidadmedida'),
        ),
    ]
