# Generated by Django 6.1.1 on 2026-10-09 10:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_seed_unidades_medida'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('proveedor'), name='producto_unico_por_proveedor', violation_error_message='Este proveedor ya tiene un producto con ese nombre.'),
        ),
    ]
