# Generated by Django 6.1.1 on 2026-10-09 11:08

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_activar_unaccent'),
    ]

    operations = [
    ]
